[package]
authors = []
edition = "2024"
name = "lingua_nif"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]
name = "lingua_nif"
path = "src/lib.rs"

[dependencies]
lingua = "1.7.2"
rustler = "0.37.2"
